version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_pdvfood
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pdvfood
      MYSQL_USER: pdvfood
      MYSQL_PASSWORD: 1234root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
